name = "cobweb-worker"
main = "src/index.ts"
compatibility_date = "2022-12-09"

kv_namespaces = [
  { binding = "COBWEB_KV", id = "3d8d5884ac32406aa098b1e0114c1a4b", preview_id = "4f68b914b2ae414fb3305f4672b101d0" },
]

[vars]
INFURA_ID = "68536930f1864c1b8e9aac67c3095ec8"
ENVIRONMENT = "production"

[env.dev]
ENVIRONMENT = "dev"
