name: Create Cobweb Release

on:
  workflow_dispatch:
    inputs:
      version_number:
        description: "Current Cobweb version number"
        required: true
        default: "v0.0.0"
      release_name:
        description: "Cobweb release name"
        required: true
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: release/RELEASE_NOTES.md
          files: cobweb.crx
          name: ${{github.event.inputs.release_name}}
          tag_name: ${{github.event.inputs.version_number}}
